# Generated by Django 4.1 on 2022-10-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='images',
        ),
    ]
