# Generated by Django 4.1 on 2022-10-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
